Update assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,10 +1,13 @@
-#!/bin/bash -e
+#!/bin/bash
+echo "Before assembling"
 
-if [ -e /usr/local/sti/assemble ]; then
-  # old assemble location in previous php image versions
-  source /usr/local/sti/assemble
-else 
-  source ${STI_SCRIPTS_PATH}/assemble
+/usr/libexec/s2i/assemble
+rc=$?
+
+if [ $rc -eq 0 ]; then
+    echo "After successful assembling"
+else
+    echo "After failed assembling"
 fi
 
-[[ -d ./tmp ]] && chmod -R go+rw ./tmp
+exit $rc
